### ISSUE TITLE
POSAwesome Scale Barcode Not Adding Item Automatically

### ISSUE THREAD

**Issue by Manaa0-0** [defendicon/POS-Awesome-V15#2366]
### Environment

chrome

### Steps to reproduce

```bash
Summary

When scanning a scale-generated barcode in POSAwesome, the system does not automatically add the item to the POS cart based on the embedded item code and weight.
Instead, the barcode is read as a plain number, and POSAwesome fails to identify the product or calculate its total price.
```

### Expected behavior

Expected Behavior

When a valid scale barcode (EAN-13 type) is scanned — for example:

6220010005008

— and the system is configured as follows:

Scale Barcode Start With: 622

Barcode Length: 13

Interpret Last Digits As: Weight

Barcode Format: PPPPIIIIIIWWWWW + CheckDigit

POSAwesome should:

Detect that the barcode starts with the scale prefix (622).

Extract the product code (00100 → item “Chess”).

Decode the weight (00500 → 0.500 kg).

Retrieve the item price per kg from ERPNext.

Automatically calculate the line item price = unit price × weight.

Add the item to the POS cart with the correct weight and total.

### Actual behavior / logs

```text
Actual Behavior

Scanning a valid scale barcode (e.g. 6220010005008) does not add the product automatically.

POSAwesome treats it as an unrecognized barcode or a regular product code.

The item is not added to the cart, or it appears with quantity = 1 instead of the decoded weight.

The system fails to calculate the price dynamically based on the weight embedded in the barcode.
```

### Pre-submit checks

- [x] I searched existing issues
- [x] I can reproduce on the latest release

**Comment by Manaa0-0** [comment]
Barcode Type CODE-39

Product Example “Chess”, Code = 100, UOM = Kg
Barcode Examples  6220010001008 (1 kg), 6220010005008 (0.5 kg)

</div></div>
<hr data-start="2118" data-end="2121">
<h3 data-start="2123" data-end="2149"><strong data-start="2127" data-end="2149">Steps to Reproduce</strong></h3>
<ol data-start="2150" data-end="2514">
<li data-start="2150" data-end="2289">
<p data-start="2153" data-end="2183">Configure POSAwesome Settings:</p>
<ul data-start="2187" data-end="2289">
<li data-start="2187" data-end="2221">
<p data-start="2189" data-end="2221">Scale Barcode Start With = <code data-start="2216" data-end="2221">622</code></p>
</li>
<li data-start="2225" data-end="2248">
<p data-start="2227" data-end="2248">Barcode Length = <code data-start="2244" data-end="2248">13</code></p>
</li>
<li data-start="2252" data-end="2289">
<p data-start="2254" data-end="2289">Interpret Last Digits As = <code data-start="2281" data-end="2289">Weight</code></p>
</li>
</ul>
</li>
<li data-start="2290" data-end="2397">
<p data-start="2293" data-end="2329">Create item “Chess” in ERPNext with:</p>
<ul data-start="2333" data-end="2397">
<li data-start="2333" data-end="2352">
<p data-start="2335" data-end="2352">Item Code = <code data-start="2347" data-end="2352">100</code></p>
</li>
<li data-start="2356" data-end="2368">
<p data-start="2358" data-end="2368">UOM = <code data-start="2364" data-end="2368">Kg</code></p>
</li>
<li data-start="2372" data-end="2397">
<p data-start="2374" data-end="2397">Price = 2500 YER per kg</p>
</li>
</ul>
</li>
<li data-start="2398" data-end="2429">
<p data-start="2401" data-end="2429">Add barcode: <code data-start="2414" data-end="2429">6220010001008</code></p>
</li>
<li data-start="2430" data-end="2462">
<p data-start="2433" data-end="2462">Open POSAwesome → POS screen.</p>
</li>
<li data-start="2463" data-end="2514">
<p data-start="2466" data-end="2514">Scan the barcode <code data-start="2483" data-end="2498">6220010005008</code> (0.5 kg label).</p>
</li>
</ol>
<hr data-start="2516" data-end="2519">
<h3 data-start="2521" data-end="2544"><strong data-start="2525" data-end="2544">Observed Result</strong></h3>
<ul data-start="2545" data-end="2684">
<li data-start="2545" data-end="2583">
<p data-start="2547" data-end="2583">No item is added to the POS cart, or</p>
</li>
<li data-start="2584" data-end="2684">
<p data-start="2586" data-end="2684">Item “Chess” is added but with <strong data-start="2617" data-end="2633">quantity = 1</strong>, not <strong data-start="2639" data-end="2649">0.5 kg</strong>, and the total price is incorrect.</p>
</li>
</ul>
<hr data-start="2686" data-end="2689">
<h3 data-start="2691" data-end="2714"><strong data-start="2695" data-end="2714">Expected Result</strong></h3>
<p data-start="2715" data-end="2761">POSAwesome should parse the barcode correctly:</p>
<ul data-start="2762" data-end="2951">
<li data-start="2762" data-end="2777">
<p data-start="2764" data-end="2777">Prefix: <code data-start="2772" data-end="2777">622</code></p>
</li>
<li data-start="2778" data-end="2811">
<p data-start="2780" data-end="2811">Product Code: <code data-start="2794" data-end="2801">00100</code> → “Chess”</p>
</li>
<li data-start="2812" data-end="2840">
<p data-start="2814" data-end="2840">Weight: <code data-start="2822" data-end="2829">00500</code> → 0.500 kg</p>
</li>
<li data-start="2841" data-end="2885">
<p data-start="2843" data-end="2885">Price Calculation: <code data-start="2862" data-end="2885">2500 × 0.5 = 1250 YER</code></p>
</li>
<li data-start="2886" data-end="2951">
<p data-start="2888" data-end="2951">Add “Chess (0.5 kg)” with total price 1250 YER to the POS cart.</p>
</li>
</ul>
<hr data-start="2953" data-end="2956">
<h3 data-start="2958" data-end="2981"><strong data-start="2962" data-end="2981">Possible Causes</strong></h3>
<ul data-start="2982" data-end="3331">
<li data-start="2982" data-end="3071">
<p data-start="2984" data-end="3071">The <strong data-start="2988" data-end="3018">scale barcode prefix (622)</strong> is not recognized internally due to missing mapping.</p>
</li>
<li data-start="3072" data-end="3170">
<p data-start="3074" data-end="3170">POSAwesome’s <strong data-start="3087" data-end="3113">scale parsing function</strong> is only checking for the first 2–3 digits (e.g., <code data-start="3163" data-end="3168">221</code>).</p>
</li>
<li data-start="3171" data-end="3249">
<p data-start="3173" data-end="3249">ERPNext’s barcode validation for EAN prevents proper linking of the product.</p>
</li>
<li data-start="3250" data-end="3331">
<p data-start="3252" data-end="3331">The system does not multiply the unit price by the parsed weight automatically.</p>
</li>
</ul>

</body>
</html>

**Comment by defendicon** [comment]
@Manaa0-0 I have fixed for manual barcode scanner but if you use 2 digits in pos awesome settings Scale Barcode Start With field then next 5 digits will be item code and the last 5 digits will be weight detection. but if you will add 3 digits in Scale Barcode Start With then you have to use 4 digits for item code and last 5 digits will be for weight. its a 12 digits scale barcode I will enhance it for EAN-13 type barcode also soon. you have to change branch to "stage-develop" for testing purpose when it will stable then I will merge it with develop branch.

**Comment by Manaa0-0** [comment]
<html>
<body>
<html><head></head><body><p></p>
<hr>
<p>@defendicon, thanks for your effort.</p>
<p>What I noticed is that the barcode <strong>can be identified in the item search field</strong>. For example:</p>
<p><strong>Scale barcode:</strong> 622</p>
<ul>
<li>
<p><strong>Current weight UOM:</strong> 1 kg</p>
</li>
<li>
<p><strong>Number of codes/chess:</strong> 100</p>
</li>
</ul>

Weight | Code
-- | --
1 kg | 6220010001008
0.5 kg | 6220010000508


<p>The inventory system has tried scanning the barcode using <strong>GS1, Code39, and EAN12</strong> — all with the same result. However:</p>
<ul>
<li>
<p>The item <strong>cannot be added</strong> or calculated in <code inline="">itemtable.vue</code>.</p>
</li>
<li>
<p>When using <strong>manual input</strong> or a <strong>hardware scanner</strong>, the following error occurs:</p>
</li>
</ul>
<pre><code>Scan Error
Item not found: 6220010

Scanned Code:
6220010001008
Please verify the barcode or search manually.
</code></pre>
<p><strong>Notice:</strong><br>
For barcodes, the usual behavior is that scanned items are automatically deleted so that new items can be added—this is especially important during crowded hours in supermarkets.</p>
<hr>

**Comment by Manaa0-0** [comment]
@defendicon hi
the scale barcode issue still as https://github.com/defendicon/POS-Awesome-V15/issues/2371#issuecomment-3487223106

**Comment by Manaa0-0** [comment]
@defendicon read this as reference https://github.com/ERPGulf/scale

**Comment by defendicon** [comment]
@Manaa0-0 Did you check new scale barcode ?

**Comment by Manaa0-0** [comment]
@defendicon I had not fully tested it but now there are two scales barcode one In pos profile and the other in the barcode scales setting

**Comment by defendicon** [comment]
@Manaa0-0 yes use scale barcode settings for scale barcode I will remove pos profile scale barcode in next version.
