### ISSUE TITLE
price not loaded properly when scanned using barcode

### ISSUE THREAD

**Issue by mohammedlutf** [defendicon/POS-Awesome-V15#2371]
### Environment

posawesome

### Steps to reproduce

```bash
The sales price not loaded properly when i scan the barcode with different uom 
For example i have an item that has two uom nos and box and i have barcode for box the price it gives me is the nos price .

2 ) with scaled barcode it is not practical to use Manual or Hardware Scanner Input when ever i want to scan a scaled barcode you can make it within search item or you can add a barcode listener no need to point the the search items field when ever i want to scan a barcode
```

### Expected behavior

/

### Actual behavior / logs

```text
/
```

### Pre-submit checks

- [x] I searched existing issues
- [x] I can reproduce on the latest release

**Comment by defendicon** [comment]
@mohammedlutf fixed. please and check now.

**Comment by mohammedlutf** [comment]
@defendicon scaled barcode is working .. but the item rate when scan the item barcode with box uom the rate comes with NOS uom the rate loaded correctly either i scan the barcode a gain or open the item info

**Comment by mohammedlutf** [comment]
https://github.com/user-attachments/assets/12f4cc95-c40c-4173-970b-f79cf4116d16

**Comment by defendicon** [comment]
@mohammedlutf could you please update again and check now in incognito mode branch "stage-develop".

**Comment by defendicon** [comment]
@mohammedlutf @Manaa0-0 I have implemented and Integrated Scale barcode please update to branch "stage-develop" and migrate site also then configure scale barcode settings in pos awesome workspace below pos profile, settings like prefix item code start item weight decimals etc. check if you get any bugs.

**Comment by mohammedlutf** [comment]
@defendicon nice work about scale barcode . I still have the issue which i have shown in the above .

**Comment by defendicon** [comment]
@mohammedlutf ok I'll check that also uom related prices.
