### ISSUE TITLE
POSAwesome Does Not Update Item Prices When Customer is Changed

### ISSUE THREAD

**Issue by ungke2505** [defendicon/POS-Awesome-V15#340]
Issue  #1
https://github.com/user-attachments/assets/613d4bac-7989-44e3-9a44-a6fdc939a5ce

Problem in Issue #1

When both Customer and Price List are defined in the POS Profile:
POSAwesome only fetches prices from the price list set in the POS Profile.
When the customer is changed during a transaction, item prices do not update automatically based on the new customer's pricing (defined in either the Customer Group or Customer's Default Price List).
The item prices shown remain the same as the original price list defined in the POS Profile, regardless of customer-specific pricing rules.

Issue #2
https://github.com/user-attachments/assets/b9a4fccd-4918-4c74-9e70-65a7dd4b237f

Problem in Issue #2
When Customer is selected but Price List is left blank in the POS Profile:
POSAwesome opens the POS screen, but all item prices (rate) are displayed as 0.
Even after selecting a customer, item prices do not update.
The price only appears correctly after adding the item to the cart and manually clicking on it inside the cart.
This causes confusion and risk of error for cashiers expecting the right price before adding items.

Expected Behavior

- If a customer is changed during a transaction, the item list should refresh and display prices based on the appropriate price list (from the customer's default or their customer group).

- If the POS Profile has no price list, the system should fall back to:

1. Customer’s default_price_list
2. Then to Customer Group’s default_price_list
3. Then to global default (Selling Settings)

**Environment**
frappe : 15.65.2
erpnext : 15.58.2
hrms : 16.0.0-dev
posawesome : 15.3.1

**Comment by defendicon** [comment]
@ungke2505 I have fixed this issue by adding price list in pos awesome invoice interface you can update pos app and then test please and tell if you want any modifications.

**Comment by Manaa0-0** [comment]
@ungke2505 

Update Instructions

After switching branches or pulling latest changes:

    cd apps/posawesome
    git pull
    yarn install
    cd ../..
    bench build --app posawesome
    bench --site your.site migrate

**Comment by ungke2505** [comment]
Thanks for your reply.

While item prices eventually update correctly when changing the customer in POS, there is a noticeable delay before the correct prices appear in the item list UI.

This occurs even when both:

✅ Customer and Price List are set in the POS Profile

✅ Use Redis Cache (posa_use_server_cache) and Use Local Storage are enabled


**Observed Behavior**
When changing the customer, item list refreshes after a 4 - 7 minutes.

Prices take 3–5 minutes (sometimes more) to visibly update on the screen.

During that time, incorrect prices (from previous customer or default) may appear briefly, which can confuse cashiers.

> [@ungke2505](https://github.com/ungke2505) I have fixed this issue by adding price list in pos awesome invoice interface you can update pos app and then test please and tell if you want any modifications.

**Comment by Manaa0-0** [comment]
@ungke2505 
We’d love to have your help improving POSAwesome—especially if you have a background in coding. We’re committed to making the app more stable and responsive, and we’d really value your feedback and recommendations. If you’re able to review our code and share comments, we’d be thrilled to collaborate with you

**Comment by defendicon** [comment]
@ungke2505 
Thank you for the kind invitation! I’d be happy to contribute to POSAwesome and help improve its functionality and stability. I dont have a background in coding but have already been working with the POSAwesome codebase in my own setup. I’d be glad to review the code, share feedback, and collaborate on enhancements. Looking forward to working together!

**Comment by defendicon** [comment]
@ungke2505 
Fixed now it is only some seconds delay if inventory has up to 2-5k items.

**Comment by Manaa0-0** [comment]
@defendicon you are the best

**Comment by ungke2505** [comment]
Hi @defendicon , thanks again for the recent improvements.

After updating to v15.3.2, I noticed that the delay issue when switching customers in the POS UI still persists. Although it has improved slightly, there is still a noticeable lag (1 - 2 minutes) before the correct item prices appear after selecting a different customer.

**Observed Behavior**
On opening POS with a predefined customer and price list → item prices load as expected
On changing the customer in POS:
Item prices remain stale for a few seconds
Correct prices appear after some delay

https://github.com/user-attachments/assets/9a06bcd7-53cd-41d1-a21f-6b4ab4c7a3ce



**Previous Working Version (15.3.1)**
I tested the commit just before 15.3.2 (commit a7b7f10), and applied this simple patch on posapp.py :

```
@redis_cache(ttl=60)
def __get_items(pos_profile, price_list, item_group, search_value):
    return _get_items(pos_profile, price_list, item_group, search_value)
```

By removing customer from the Redis cache key, prices started updating instantly again when switching customers.


https://github.com/user-attachments/assets/c0dce5ea-6cf8-409d-97c6-686aac257fff



Tested Environment
POSAwesome version: 15.3.2
Redis cache enabled (posa_use_server_cache = 1)
Inventory size: ~2,000 to 5,000 items


Note:
It’s currently 4:00 AM in my local time, so I’ll continue testing and reviewing this further tomorrow. Just wanted to give early feedback based on today’s results.

Thanks again for all your efforts — I really appreciate the work on POSAwesome 🙌

**Comment by defendicon** [comment]
@ungke2505 please enable price list drop down in posawesome advance setting in pos profile.

**Comment by defendicon** [comment]
@ungke2505 did you check price list feature ?

**Comment by ungke2505** [comment]
Hi @defendicon 

After testing the latest version (v15.3.2), we confirmed that prices do eventually change when switching the customer, but there is still a significant delay of around 1–3 minutes before the correct prices appear in the UI.
This delay becomes especially problematic when we have 5,000+ active items in the system.

We tested with:

- POS Profile that has both Customer and Price List set.
- We also tried toggling the Price List dropdown in POS Profile.

In all cases, the backend returns the correct price eventually, but the UI continues to show outdated prices, due to caching or slow refresh.


What we changed to fix it:
1. **In ItemSelector.vue → Add these watchers:**

`watch: {
  customer() {
    // Always fetch new items from server when customer changes
    this.items_loaded = false;
    this.get_items(true);
  },
  customer_price_list() {
    // Always fetch new items when price list changes
    this.items_loaded = false;
    this.get_items(true);
  },
  new_line() {
    this.eventBus.emit("set_new_line", this.new_line);
  },
  filtred_items(new_value, old_value) {
    // Update item details if items changed
    if (!this.pos_profile.pose_use_limit_search && new_value.length !== old_value.length) {
      this.update_items_details(new_value);
    }
  },
}
`

2. **ItemSelector.vue – Force reload logic in get_items(force_server)**

`  if (force_server && this.pos_profile.posa_local_storage) {
      localStorage.setItem("items_storage", "");
    }

    let search = this.get_search(this.first_search);
    let gr = vm.item_group !== "ALL" ? vm.item_group.toLowerCase() : "";
    let sr = search || "";

    // 🧠 Skip reload hanya jika tidak force, tidak search, dan items sudah dimuat
    if (
      this.items_loaded &&
      !force_server &&
      !this.first_search &&
      !this.pos_profile.pose_use_limit_search
    ) {
      console.info("Items already loaded, skipping reload");
      if (this.filtered_items && this.filtered_items.length > 0) {
        this.update_items_details(this.filtered_items);
      }
      this.loading = false;
      return;
    }

    // ✅ Ambil dari localStorage hanya jika tidak force_server
    if (
      vm.pos_profile.posa_local_storage &&
      getItemsStorage().length &&
      !vm.pos_profile.pose_use_limit_search &&
      !force_server
    ) {
      vm.items = getItemsStorage();
      this.eventBus.emit("set_all_items", vm.items);
      vm.loading = false;
      vm.items_loaded = true;

      setTimeout(async () => {
        if (vm.items && vm.items.length > 0) {
          await vm.prePopulateStockCache(vm.items);
          vm.update_items_details(vm.items);
        }
      }, 300);
      return;
    }

    // 🛰 Fetch dari server
    frappe.call({
      method: "posawesome.posawesome.api.posapp.get_items",
      args: {
        pos_profile: vm.pos_profile,
        price_list: vm.customer_price_list,
        item_group: gr,
        search_value: sr,
        customer: vm.customer,
      },
      callback: async function (r) {
        if (r.message) {
          vm.items = r.message;
          vm.eventBus.emit("set_all_items", vm.items);
          vm.loading = false;
          vm.items_loaded = true;

          console.info("Items Loaded");
          await vm.prePopulateStockCache(vm.items);

          vm.$nextTick(() => {
            if (vm.search) vm.search_onchange();
          });

          setTimeout(() => {
            if (vm.items && vm.items.length > 0) {
              vm.update_items_details(vm.items);
            }
          }, 300);

          // ✅ Simpan ke cache baru
          if (
            vm.pos_profile.posa_local_storage &&
            !vm.pos_profile.pose_use_limit_search
          ) {
            try {
              setItemsStorage(r.message);
            } catch (e) {
              console.error(e);
            }
          }

          if (vm.pos_profile.pose_use_limit_search) {
            vm.enter_event();
          }
        }
      },
    });
  },`

3. **In posapp.py → Fix limit logic when searching**

` if use_limit_search:
            search_limit = pos_profile.get("posa_search_limit") or 500
            data = {}
            if search_value:
                data = search_serial_or_batch_or_barcode_number(
                    search_value, search_serial_no
                )

            item_code = data.get("item_code") if data.get("item_code") else search_value
            serial_no = data.get("serial_no") if data.get("serial_no") else ""
            batch_no = data.get("batch_no") if data.get("batch_no") else ""
            barcode = data.get("barcode") if data.get("barcode") else ""

            condition += get_seearch_items_conditions(
                item_code, serial_no, batch_no, barcode
            )
            if item_group:
                condition += " AND item_group like '%{item_group}%'".format(
                    item_group=item_group
                )

            ## Use limit search if search_value is provided
            if not search_value:
                limit = " LIMIT {search_limit}".format(search_limit=search_limit)
            else:
                limit = ""
`
Final Result
- Prices now update instantly when switching customer or price list.
- No more UI freeze or delay.
- Works well with large datasets (5,000+ items). Respects localStorage caching properly, with safe invalidation


##Video

https://github.com/user-attachments/assets/6d0ba250-df78-423b-9d85-c2a6a0e71e31


[posapp_itemselector.zip](https://github.com/user-attachments/files/20777979/posapp_itemselector.zip)

And again.., 
Thanks for your awesome work on POSAwesome! 💪

**Comment by Manaa0-0** [comment]
@ungke2505 thanks for your feedback

**Comment by Manaa0-0** [comment]
@ungke2505 we pleased to invite you telegram group where we discuss the improvement for POS Awesome https://t.me/posawesome

**Comment by defendicon** [comment]
@ungke2505 Thanks I have implemented your given code and it is awesome (Y)

**Comment by ungke2505** [comment]
> [@ungke2505](https://github.com/ungke2505) we pleased to invite you telegram group where we discuss the improvement for POS Awesome https://t.me/posawesome

Thanks @Manaa0-0.
Joined.
